name: sample
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - jupyterlab
  - pandas
  - python=3.12
  - scikit-learn
  - scikit-plot
  - seaborn
  - pip
  - python-dotenv
  - ydata-profiling
